# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0WhaIebPGtQTM1fSN9jnvZX7Q8qlAv0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df= pd.read_csv('final_internship_data.csv')

df.shape

df.info()

df.head()

# Remove invalid values
df = df[df['fare_amount'] > 0]
df = df[df['distance'] > 0]
df = df[df['passenger_count'] > 0]

# Handling Missing Values
df.isnull().sum()
(df.isnull().sum() / len(df)) * 100  #percentage of nulls
df.dropna(inplace=True)  # delete nulls becuase there are very few
df.isnull().sum()

# Check duplicate rows
df.duplicated().sum()
# there are no duplicates

#determine categorical variables
df.select_dtypes(include="object").columns

# Encoding Categorical Variables

# Remove unnecessary columns
df.drop(columns=['User ID', 'User Name', 'Driver Name', 'key', 'pickup_datetime'], inplace=True)   #delete categorical variables which not affect

# One-Hot Encoding for Weather becuase it's nnominal
df = pd.get_dummies(df, columns=['Weather'], drop_first=True)

# Ordinal Encoding for Traffic Condition because it's ordinal
traffic_map = {
    'Flow Traffic': 0,
    'Dense Traffic': 1,
    'Congested Traffic': 2
}

df['Traffic Condition'] = df['Traffic Condition'].map(traffic_map)

# Ordinal Encoding for Car Condition  because it's ordinal
car_map = {
    'Bad': 0,
    'Good': 1,
    'Very Good': 2,
    'Excellent': 3
}

df['Car Condition'] = df['Car Condition'].map(car_map)

# Check the result
df.head()

# Remove outliers using IQR

columns = ['fare_amount', 'distance']

for col in columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

# Feature Selection using RFE
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

# Splitting Features and Target
X = df.drop('fare_amount', axis=1)
y = df['fare_amount']

# Save original feature names
feature_names = X.columns

# Create Linear Regression model
model = LinearRegression()

# Apply RFE
rfe = RFE(estimator=model, n_features_to_select=10)

# Fit RFE
rfe.fit(X, y)

# Show ranking of all features
feature_ranking = pd.DataFrame({
    'Feature': feature_names,
    'Selected': rfe.support_,
    'Ranking': rfe.ranking_
})

print(feature_ranking.sort_values('Ranking'))

# Keep only selected features
selected_features = feature_names[rfe.support_]
X = X[selected_features]

print("\nSelected Features:")
print(selected_features)

# Split train and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

# Cross validation
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    pipeline,
    X_train,
    y_train,
    cv=5,
    scoring='r2'
)

print(cv_scores)
print(cv_scores.mean())

# train the model
pipeline.fit(X_train, y_train)

# predection
y_pred = pipeline.predict(X_test)

# model evaluation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("RMSE:", rmse)

r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

# ==========================
# Hyperparameter Tuning
# Ridge Regression + GridSearchCV
# ==========================

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


# Create Ridge Pipeline
ridge_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', Ridge())
])


# Parameters to test
param_grid = {
    'model__alpha': [0.001, 0.01, 0.1, 1, 10, 100, 500, 1000]}


# Apply GridSearchCV
grid_search = GridSearchCV(
    estimator=ridge_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='r2'
)


# Train and search for best parameter
grid_search.fit(X_train, y_train)


# Best parameter
print("Best Parameters:")
print(grid_search.best_params_)


# Best CV score
print("\nBest CV R2 Score:")
print(grid_search.best_score_)


# Get the best tuned pipeline
best_model = grid_search.best_estimator_


# Prediction using tuned model
y_pred_tuned = best_model.predict(X_test)


# Evaluation after tuning
mae_tuned = mean_absolute_error(y_test, y_pred_tuned)

rmse_tuned = np.sqrt(mean_squared_error(y_test, y_pred_tuned))

r2_tuned = r2_score(y_test, y_pred_tuned)


print("\nTuned Model Evaluation:")
print("MAE:", mae_tuned)
print("RMSE:", rmse_tuned)
print("R2 Score:", r2_tuned)

# ==========================
# Model Comparison
# Before vs After Tuning
# ==========================

results = pd.DataFrame({
    'Model': ['Linear Regression (Baseline)', 'Ridge Regression (Tuned)'],
    'MAE': [mae, mae_tuned],
    'RMSE': [rmse, rmse_tuned],
    'R2 Score': [r2, r2_tuned]
})

results

import joblib

joblib.dump(pipeline, "taxi_fare_pipeline.pkl")